mysite/mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
	url(r'^website/',include('website.urls',namespace='website')),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/mysite/website/urls.py
from django.conf.urls import patterns,url

from website import views

urlpatterns=patterns('',
	url(r'^$',views.IndexView.as_view(),name='index'),
	url(r'^(?P<pk>\d+)/$',views.DetailView.as_view(),name='detail'),
	url(r'video$',views.VideoView.as_view(),name='video'),
	url(r'picture$',views.PictureView.as_view(),name='picture'),
	url(r'beauty$',views.BeautyView.as_view(),name='beauty'),
	url(r'(?P<data_id>\d+)/comment/$',views.comment,name='comment'),
)

mysite/mysite/website/models.py
from django.db import models
import ast
# Create your models here.

class Data(models.Model):
	vtag=models.BooleanField(default=False) #'v' for video,'p' for picture,'a' for article.
	btag=models.BooleanField(default=False)
	ptag=models.BooleanField(default=False)
	date=models.DateTimeField('published_time') #The time we published the data.
	title=models.CharField(max_length=20000) 
	text=models.TextField()#The description of the video.
	def __str__(self):
		return self.title

class Url(models.Model):
	data=models.ForeignKey(Data)
	text=models.CharField(max_length=2000)
	is_cover=models.BooleanField(default=False)
	def __str__(self):
		return self.text

class Comments(models.Model):
	data=models.ForeignKey(Data)
	text=models.TextField()
	email=models.EmailField()
	name=models.CharField(max_length=2000)
	date=models.DateTimeField('comment_time')
	def __str__(self):
		return self.text
		

mysite/mysite/website/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse,HttpResponseRedirect
from django.template import RequestContext,loader
from django.shortcuts import render,get_object_or_404
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from website.models import Data,Url,Comments


class IndexView(generic.ListView):
	template_name='website/index.html'
	context_object_name='data_list'
	def get_queryset(self):
		return Data.objects.order_by('-date')[:25]
		
class DetailView(generic.DetailView):
	model=Data
	template_name='website/detail.html'
	
class VideoView(generic.ListView):
	template_name='website/index.html'
	context_object_name='data_list'
	def get_queryset(self):
		v_list=Data.objects.filter(vtag=True)
		return v_list
		
class PictureView(generic.ListView):
	template_name='website/index.html'
	context_object_name='data_list'
	def get_queryset(self):
		p_list=Data.objects.filter(ptag=True)
		return p_list

class BeautyView(generic.ListView):
	template_name='website/index.html'
	context_object_name='data_list'
	def get_queryset(self):
		b_list=Data.objects.filter(btag=True)
		return b_list
		
		
def is_email(str):#judge if a str is an email.
	import re
	if re.match('\w+@\w+.\w+',str):
		return True
	else:
		return False
	
	
		
def comment(request,data_id):
	data=get_object_or_404(Data,pk=data_id)
	comment_name=request.POST['name']
	comment_email=request.POST['email']
	comment_text=request.POST['text']
	if not is_email(comment_email):
		return render(request,'Please input a real email address!')
	if not comment_name:
		return render(request,'Please enter an valid user name.')
	comment=Comments()
	comment.name=comment_name
	comment.email=comment_email
	comment.text=comment_text
	comment.date=timezone.now()
	comment.data=data
	comment.save()
	return HttpResponseRedirect(reverse('website:detail',args=(data.id,)))
	

mysite/mysite/website/templates/website/detail.html
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<link href="{% static 'website/index.css' %}" rel="stylesheet" type="text/css" media="all"/>
<div class="all">
	<div class="top_banner">
		<a class="top_banner_name" href="{% url 'website:index' %}">噗哈哈哈</a>
		<a class="top_banner_tag" href="{% url 'website:video' %}">视频</a>
		<a class="top_banner_tag" href="{% url 'website:picture'%}">图片</a>
		<a class="top_banner_tag" href="{% url 'website:beauty' %}">美图</a>
		<p class="banner_text"><i>搜集网络上好玩有趣的东东！</i></p>
	</div>
<div class="detail_title">{{data.title}}</div>
<hr width="500" align="left" color=#E0E0E0>
<!--<hr width="500" align="left" color=#E0E0E0>-->
<div class="detail_date"><i>发表于：{{data.date}}&nbsp&nbsp&nbsp&nbsp{{data.comments_set.all.count}}位童鞋发表了评论</i></div>
<br>
<!--<hr width="500" align="left" color=#E0E0E0>-->
<div class="detail_text">{{data.text}}</div>
{% if data.vtag %}
	{% for url in data.url_set.all %}
		<br>
		<div class="content_url">
			<embed src="{{url.text}}" allowfullscreen="true" quality="high" width="700" height="427" align="middle" allowscriptaccess="always" type="application/x-shockwave-flash">
		</div>
	{% endfor %}
{% endif %}
{% if data.ptag %}
	{% for url in data.url_set.all %}
		<div class="content_url">
			<img src="{{url.text}}"/>
		</div>
		<br>
		<br>
		<br>
		<br>
	{% endfor %}	
{% endif %}

<div class="comment_first"><B>已经有{{data.comments_set.all.count}}位小伙伴发表了评论哦！</B></div>
{% for comment in data.comments_set.all %}
	<hr width="500" align="left" color=#E0E0E0>
	<div class="comment">
		<div class="comment-user">{{comment.name}}童鞋 说：</div>
		<br>
		<div class="comment-text">{{comment.text}}</div>
		<br>
		<div class="comment-time"><i>发表于：{{comment.date}}</i></div>
	</div>
{% endfor %}
<div class="comment_form">
<hr width="500" align="left" color=#E0E0E0>
<br>
	<form action="{% url 'website:comment' data.id %}" method="post">
	{% csrf_token %}
	姓名：<input type="text" name="name"/>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp邮箱：<input type="text" name="email"/>
	<br>
	<textarea rows="10" cols="70" name="text"></textarea>
	<br>
	<input type="submit" value="发送评论" style="width:90px;height:30px" size="20px"/>
	</form>
</div>
<div class="end">
	<br>
	<br>
	<br>
	本站不提供任何上传服务，所有内容均来自网络上的公开引用资源
	<hr>
	联系邮箱:puhahaha@163.com
	<br>
	<br>
</div>
</div>

mysite/mysite/website/templates/website/index.html
{% load pagination_tags %}
{% load staticfiles %}
<html xmlns="http://www.w3.org/1999/xhtml" lang="zh-CN">
<link href="{% static 'website/index.css' %}" rel="stylesheet" type="text/css" media="all"/>
<div class="all">
	<div class="top_banner">
		<a class="top_banner_name" href="{% url 'website:index' %}">噗哈哈哈</a>
		<a class="top_banner_tag" href="{% url 'website:video' %}">视频</a>
		<a class="top_banner_tag" href="{% url 'website:picture'%}">图片</a>
		<a class="top_banner_tag" href="{% url 'website:beauty' %}">美图</a>
		<p class="banner_text"><i>搜集网络上好玩有趣的东东！</i></p>
	</div>
	<div class="content_left">
	{% autopaginate data_list 5 %}
	{% if data_list %}
		<ul class="content_left">
			{% for data in data_list %}
				<br>
				<br>
				<li class="content_all">
				<div class="content_title">
					<a class="content_title" href="{% url 'website:detail' data.id %}">{{data.title}}</a>
				</div>
				<hr width="480" align="left" color=#E0E0E0>
				<p class="content_text">
					{{data.text}}
				</p>
				{% if data.vtag %}
					{% for url in data.url_set.all %}
					<div class="content_url">
						<embed src="{{url.text}}" allowfullscreen="true" quality="high" width="480" height="405" align="middle" allowscriptaccess="always" type="application/x-shockwave-flash"/>
					</div>
					{% endfor %}
				{% endif %}
				{% if data.ptag %}
					{% for url in data.url_set.all %}
						{% if url.is_cover %}
						<div class="content_url">
							<a href="{% url 'website:detail' data.id %}"><img src="{{url.text}}" width="480"/></a>
						</div>
						{% endif %}
					{% endfor %}
				{% endif %}
				{% if data.btag %}
					{% for url in data.url_set.all %}
						{% if url.is_cover %}
						<div class="content_url">
							<img src="{{url.text}}" width="480"/>
						</div>
						{% endif %}
					{% endfor %}
				{% endif %}
				<hr width="480" align="left" color=#E0E0E0>
				<div><i class="content_date">{{data.date}}</i>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a class="content_comment_number" href="{% url 'website:detail' data.id %}">有({{data.comments_set.all.count}})位童鞋发表了评论</a></div>
				</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No data here!</p>
	{% endif %}
	</div>
	{% paginate %}
	
	<div class="end">
	<br>
	<br>
	<br>
	本站不提供任何上传服务，所有内容均来自网络上的公开引用资源
	<hr>
	联系邮箱:puhahaha@163.com
	<br>
	<br>
	</div>
</div>
</html>